name = "NVIDIALibraries"
uuid = "455bb3cc-869f-42f8-aad9-fcdd684af481"
authors = ["Michael Jin <mikhail.jin@gmail.com>"]
version = "1.0.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
